apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: risk-scoring-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA+q6U+0gtHtJeViEDvQWLZJz3ou0lH8gjUM0INn6igj6itNj8ihjroQnApBw4MdpQ7YdY8DlRjkqhQl+VdlgJtlDLFSy1SN+uR0uHA5+WFHuW3oZIp3O4iDbmkNX+cfyWU2RsCxrN4jOKEw+YmKGsNwC32j/0E5Ocd3R9nn8/JSlXvE9S4fQVlazwlc1hgdl44C28mj5YYtHa1yJRzGCB3UpgDudU538Gj3OgIL7pmbo4F0mRSVslcmCRXpy+Eoay4mQnNLAJYye2UkusrTBhTlZ3W7gEMm3Fy/Tkx+/pTpEqlxr6Ou6cW5hOBMLABAaNeGCpQNSiIq+xCWFcoXyU3X1/Or4CfJjbe7OmArRvaITmDFtzIKLkUeU+UWYTY8Or904j+3wqiOESm4ihCdVXUaFf/DMBeBFrobnqwma2MVuteofi93mo6WxjOseosmEkdxKLYmW1jnkJseEIJ5mk6e+a0nFh7T5QBGlqIiGFGHO40c13dwD7XOOl23cQkgi1Sy5d7Gg7u/msIqiSXaz2Wxd/HQZR7yLVvxEoAP0si/5g4WTRjFAgM2CTX3NO+KorO8CbYehYMc/BZqrjL71m/+YMgCu54zDRJ8inx4a1Xb5JpFcn4zH6WU0DDOogQfOZjl7g0eB/ZrHB9wYh28HVV4MuOrB6/A/Ffung/bs8BJ25l2vterve1YOmxMb4kbgo7Dlki5YhwTJ4G5DMNdpOQTWllTwe+fV2et7BVLrFcIzAzp8aUdzlp9tVHOQ9neOiXYgvvfaplqOG3eg8hd6dQGCeCwEBO7UZo9mI0AzXlWiinA1UOBVYnuyQJRtlQbt/Ms22kn8Is6v8LKbWe21+mpxK75vbQzOYPev48YOJ54D4MsoGrvBFDSYD824tOFDSieaU8o7yOZ3c+QRZL5gI/4X0ODRdUhp4TJglFumlk14yvYUtG5p3uhytGXjdz9Jk2c+vLs+nn5fgoJg7aXW3fa7CAv+3L4BT+g5LUuhQErTE8+TkhumzDrkyieaQgZXW+OoBQFBbhK25/T2odocpyjI/kDC4xCQJNXbMSEs9SMG7QkbNjwaLPeCj0IQ+yoauRNIvJsQAAK1kMmFAXVjX+sKoEjOlKnQpQTJjgpzdxuEjGeVZxYE2xrL03PsPmpZgjDKlXdPGFhZkW8gBOHIar18TWpx/M4lzxtaN1XFHO1alffqJxsnCTviVCJ05XJ68OumpDV2JsaL34n8LtbgbJ6fny7TEEPP2NWDHgepYQMz6/8EYciPwoDtCY4inHwJfVTDSyUxVGZ3QSGE4i6ja2ToahzVqIjlrUopFv+yx1ozNhepNjTW6Du7vP3bCBhljV9qtN3aM7+6cZGAnaIEJ5C4WFDDPv3qIdDmE0tR0qmr9ACrdUv/XpJJGA0dUZpUU1HKUAFmTxzrw1zbLLz0cFZ65j15SaiWJitTGnORHYy24OEWxnyvPDw8kKn3uQFoz346HbDW5hqMB0h5l09uq2Ff5jobT2o2Kb4KmNhG3MqZERkeFPJ+Yz1/jFZW5x2pK0vs75ZS7h7zgex86WBb0qfvH4jd+N1pfnxG36njxvnugZqnHvkOEc+Spa3CcwmOjanJsDHcXgXynuM81hcR2ObXFy8OhaKnpcNH5Fr+7+Jw/9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: risk-scoring-cicd
    type: kubernetes.io/dockerconfigjson

