apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 2d74ea766c9a1a6bb71b0a5f3d5e714f7f0f9e88
    app.quarkus.io/build-timestamp: 2021-09-03 - 18:43:37 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: credit-origination-app
    app.kubernetes.io/version: 1.0.0
  name: credit-origination-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: credit-origination-app
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP