apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-credit-origination-app
  name: ads-risk-scoring-dev-app-credit-origination-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: ads-risk-scoring-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/ads-risk-scoring-dev/apps/app-credit-origination-app/overlays
    repoURL: https://github.com/jbcodeforce/ads-risk-scoring-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
