apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: cp4ba
  name: cp4ba
  namespace: openshift-gitops
spec:
  destination:
    namespace: cp4ba
    server: https://kubernetes.default.svc
  project: risk-scoring
  source:
    path: environments/cp4ba/env/overlays
    repoURL: https://github.com/ibm-cloud-architecture/ads-risk-scoring-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""