apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: risk-scoring-stage-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: risk-scoring-stage
    server: https://kubernetes.default.svc
  project: risk-scoring
  source:
    path: environments/risk-scoring-stage/env/overlays
    repoURL: https://github.com/ibm-cloud-architecture/ads-risk-scoring-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
