#!/bin/bash

NS=sealed-secrets
CTL_NAME=sealed-secrets-controller

function generateSecret(){
    cat $1 | kubeseal --controller-namespace  $NS \
    --controller-name $CTL_NAME --format yaml > $2
}

cd ../secrets

generateSecret docker-config.yaml docker-config-sealed.yaml 
generateSecret git-host-access-token.yaml git-host-access-token-sealed.yaml 
generateSecret git-host-basic-auth-token.yaml git-host-basic-auth-token-sealed.yaml
generateSecret gitops-webhook-secret.yaml gitops-webhook-secret-sealed.yaml
generateSecret webhook-secret-risk-scoring-app.yaml webhook-secret-risk-scoring-app-sealed.yaml

