#!/bin/bash

SECRETS_DIR=config/ads-risk-scoring-cicd/base/09-secrets

if [[ -d $SECRETS_DIR ]]
then
    mkdir $SECRETS_DIR
fi 

cd ../secrets

mv docker-config-sealed.yaml ../ads-risk-scoring-gitops/$SECRETS_DIR
mv git-host-access-token-sealed.yaml ../ads-risk-scoring-gitops/$SECRETS_DIR
mv git-host-basic-auth-token-sealed.yaml ../ads-risk-scoring-gitops/$SECRETS_DIR
mv gitops-webhook-secret-sealed.yaml ../ads-risk-scoring-gitops/$SECRETS_DIR
mv webhook-secret-risk-scoring-app-sealed.yaml ../ads-risk-scoring-gitops/$SECRETS_DIR

cd ../ads-risk-scoring-gitops
oc apply -f config/ads-risk-scoring-cicd/base/09-secrets/docker-config-sealed.yaml 
oc apply -f config/ads-risk-scoring-cicd/base/09-secrets/git-host-access-token-sealed.yaml
oc apply -f config/ads-risk-scoring-cicd/base/09-secrets/git-host-basic-auth-token-sealed.yaml
oc apply -f config/ads-risk-scoring-cicd/base/09-secrets/gitops-webhook-secret-sealed.yaml    
oc apply -f config/ads-risk-scoring-cicd/base/09-secrets/webhook-secret-risk-scoring-app-sealed.yaml